apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgC32Nf93RF6FrfyCHqv+oNpLhCbaH8DoD29jfeaY+SRfddb9H/YCH/54MMAsAstieWs0ByiwqkeAc0CVK60l/u69rVxI48IszFumQB3+AgkGViH7cFOtQSDSjFOL1lFSy39c70parsK6Srakg6iqC6r5cR8Ex40tk9CTWQh7yj1dd9ciulzAgYFegs0j7CvbqIIms3CMHFps5XPAMpscK0EPww4K8Quvp79/3PAQiuF+bdp9HStSCV+cd0+V9NpPEc8HM8BytfkP1AW9uqiyCtfaQjVonV7kjUzdLfr7dlBZWRgikWimqjVb+5Ze+QUwYyE7e7CJDL0qlt2Wfw+z28/auj1NYXO9HDw/cjMxV5l8dPKPmeGqqkK3PJdknB6ShL3Y86AwK/0jbwCq3b6HS4cGte4oKvwJvXNTFf02Stfn+Z4jw4AVZxgIauXQSk8/xlhnkmwunTAbicyY2VSKJIgoGThuZ9Or6ZwmZ1JlVzJhL6Axvt9C8oL/+NCtEOdmCe86O8pn0W1DybpRk3KurkOacavyv4V64YyLe+7vFeEaTNLNaSOGe7W3qCPz4bnaVtySwz6DeFHDJVQxLqShyPnZx+sr3IBGjzxXHIdRvmTMGtf10tjB9xnKSy2vuSki2WjILx10EwFmohNY/bWah6PNVSaS51dPbF4WRlG9RCynUAVGRBIB8a6bLPQmvncZKjVDursNHHdipY9/GcsUwkMAfEBr/TwDqaCj2EjfpPS1YHftwH+fsBrnS2babsyHCyN4sMfe7yUJr9aZLaK2wdwWsQIr2bPKZDaP3YADu1pTRFwxAofCfh1rKkjQ39tyQhvcjk/SnCYDSjwQuV4oKhdwkmklJFUoBNpk9JmyXHrNO3KwV8qMm4afJTegwArTdweAWqGGGCI
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

