apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCcygmn82yvuP5y7s3fsfHkUCv5aU41VYUmfI+FJGxlCEvcBfU/s7kj2DubgnEJa2bi4aMmHjEDt1LWcBxIx7U7lllc+c2+78qQEfUkwaaHb7SC5cAXzYX856w4VXVUCoWqCSwScoxxT2gPaCUbY4/MaTWyLRhIHtbAIwAlgN2sESvs2Oe9eN5W8RjQY9piWi4tbT3XVZt1xGrysp4Eb7Ptxd8QruTYxTSuAJdvAz69+oLWRDVnrTA6yHFeMu1mjIEckmRXbs23ZmuVB2uCoTrs+Wu9WMYlHAmJL57oE7MvzyciG4Ph3qDG8gRzWEVzU/Lop9iWSQXxV2VWG8jFg/aJSR0cuYNOdFdeSdy4oHvhfsr+fHlDw+95xyjbe1BpnoXDE1W5pCuJB05++ZXGE5prqLf+bnXtBUFNpPjadLQnvujOW3O8JNSu34Sb8pNgwMwbV962jFhybL3ZQ2X7NGLebPKChvppjRhb6NgX89mgVcey27q5IyEBL1/yuIvqpS9BP/7QM+j380eMyTLpg73DNA3a7wKlliYYSw4zccB889AU5QV7tvf8Ru8lINlJaZOtwc7trcVrY1GPdsTuW3n8Q/3Cj8Oh0isd0Jds0fPQZl4uleMep9bH2g+qQapSwczg9wW+WeQ3zquRI4N9RmYrLiWYaS7VMMnkjo69G/2de3WcxNJmzW7EYjYySUK+OS6SNTRcpY4En4xBwDHBGml8aSsIja0/Z2xYHdCaBz6Zj8dyNAeGELCopQihdsg00DJ4jBHtkBnHxk3vHCsWT6/PZQczHCGB5/ead1/WwJwdwFZRDqUgPfyPmxCFTdYr22FonO2fjBaRrffCsD3KE4dQqx2fKejPEYotK8s6trXUSxP5ACXZjsyDGXo1wWGZblgF6098GJvP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

