apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCBvE3a48hxPJGDsPR4ieOdu39FwN++J8sVaPcLEJ2y+Fo646Gsm1uXazVvXC1CYGVBdG1w5J7Ay1tsV4QkiJbfw1wt75Ywj05oUMHJw/N2Cr36QyIeVJgQZo8QvPQKAVKZwBcCFR2b9Urjft4oSmb9qOteBp0lA+8VCF1MXvI0Oab49D6Q5rvfoXMFNg1vYTp8tVb1ewbcm6+dSXkDVhlHd1ss8+b4KkTV0OZ8WHrDPHIbBYuD7simRFLLNgrsn9BOBrGO1WtZpTAOr+jsXuHSwAMHhdeMGVpgWKZPy0qE+L22AWiilNGJrf0Ip91chjU2mXIjLosbwrzbK702lU2rJBMNz/g6gcqXgXq2CuQdd6iiU8vPWNnR3MI5/0l9l3JTtov6LnUYXR1IGhePE84rC9xtsZLWibwerXCJO8cwfihvqJgt8x3aJ9Wf3hJ0uthIWKOXu443y/Sdjm2DRUNzvoN7teNzlD9bK2YR7uNezV86XPPRzShZ5gxD3jJ0lpI27pt4pgrafGAJ8rcVgeIPcNlYYFVb3bHHCGhr3NduIWfifUxp1a53XWH8NLGJlXc9use2VQ9+xfqXqPb8nkr8UH2OwdlR/HH01zcG+xn6N4ShDxJMDPMSKltd2M16c9tAJEgtlPl6ks2ldC813e+cRGqOExgwOv5esTlaNfgQ4747a825AF6PSO9v22lIBqp+F6j9Gibx6epKgl1umU8Vb9EPn15s8pSxO3UMcGrWfo2Hg3umJ0OrxeIL921F0EAUIOTwg4+S7BlsqNyvBq5+xrhk306cggjRK4/b7sBYEV5XpHYG2Al6+gB2ZchQq+Qfi18ic/si0bwaZIyaZWqXgNaq045EArqE+MhgoMOObppPzWq9Wq852An4BgGCBu0VltDrXyL5
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

