apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAabQr5FrGTcgoHdugiSmxDd5DkcgfifNPvQk1zhnc6BK+vDOSE9YF2KjEulN8z5cQFtLJ+zzug/SFcO47Rz8DcZGZMk5U2rufwZ16blAYLJDETTfHNPuH0uF3+KJmZG9kRbJYCZaPKSSQhlNB8IbxLRACQJG33zPgZwHsz5zI0XyURXbIo3iQjei0AWNnPj+h0cBe0ejQzFsgUC7xc2ia3HJ7rXg3/fB4HhH3tpJRUASkCDV9cjrhEAIV5J27pagfVsn7RebUbWUWcn/R5UnmDN/BdZSCgjqQYEam05xLewCwckJOocBuPdhfbVlg5kaEpvg7uHDlBSPU/j3KnrsMbsVjOZY6TVHKYjMZR0yNkAm3hm+LbOaiOhMIx+eVOwArcKCqvqbiDwhbKi0DBlHj9OdCjLuaDdWkKu1c3rxKGcmLavyKbUrm97xrPOrWDVVoBic5UbZBBBmqPrt1p3/PHQLlTykTKz7wKSiWfx9IaRHm/rMgyffK8dmbmhYUfIoGUDSkolIAjxpRXxX9QNrylllnbnLazF0GLzLRnqQ1v7ENYt9kBZQThQIt38Uu0xdRbDYW4i08xAXWZrybQ0MPs6T9kbBs45CPfQhdzReMyTrFD7cMqnC5Ou+IFsaWl1h9Km4wjisY9xKM72eO/dNi0uWoPsirnF8lLUsGvTEhMCVZZh4MDwO7k1QShHTUpvhx3UnO+OF93wUCHQ3RR9ktLNagKdMJrMDcofgLWVNcC0zIQdJArL/KWxKMIzhAmkt5dPt73ZVDNTEdgFIY33XG/WDhbljUunUNKMXn4RAH2kTmc6QFMRmu4xBQlXatc14n8kyu7weoFr3NR/9CR6yQXaqMlmASGOXTMXfjr54ve/QZ5/vglDY+TDfiinW+zn1fEa3p2oagg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

