apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgB7MH/cJsbdJMc7Xls0tMuE03RJhwDSt1KxiEDQGDinlXow34vFVyF+uPF6+nP4dbJnKoxyyIU5LuzV1KBHNzKGxXo18svTKnTm9hchJ+5jLizfeZBWb+y37hSTR3e/MzAIYrRSaRCZt6AwF9E9Wgsyco+Am7wgs9ooqXgB/lfckHfjvImKSKeRvjjDYsm48/EmX1cjNe9ybE7UfsvKN99OPBENl4kU/jAs/0t0MtzW0Q0RVQXS6JG2yhC9WdfixFsG3sHGc4dcrXRsRwBtKszrHVTx9+6ydCtmO8erGnfZG1DDwCFS0TW+MWk49MTj96Aq7TvVX+hbA63hFxAZ00iQf81tBiUkmsD4Y6+6cMsa3D/6k7X9XWlrqFlwu/TixSeCp3aMPg7nD3FIttdwCh8YDUMLArs+gSnhoCXvQGTxMi1tSUJRIIBRgY5yx5QiWxq9S3xD6ISlhs6TRu24hM95OwvJBX3DY11rHxEKFS2t+c3cQPomq2Fhr6MFataVxouFF/DhQjNiQAgec1RVUGnW6PXZzeyAXI6BzJANpOs1UCWTHUM/o5vJz7o3N1NGNzWZBWTp30t+gC/Gd4IB5DJNqhuz3gkAqfQ/et7aNaGWC2yoAJX3INEDZC/UNJEbcpSdYXnhjPY4kUzbs+AXbBiGxHXmZumini7eabgDeyyhJN8JHAtljIZEVeV1iYO+S3DQMgyiaC46Y/QiXM2CfMg/nB3i51aayFr8zIkoDdYl6LeuU4Go1ePJggOJuMKlHI/nJYn9IbWPU9j3jmdeuNglejlSP0qqp8wT7MK30P7nD+IBk2rK85TuWK+drURdTsq2DxbArnDcU8/K2PYSz2wk7KX60ibQr2XJZyhrr/gxbAaAU3ynAefFYa0yNJSkgqMIfV8weRqf
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

