apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBSBb5qxDMyAqhDx8EbgPHRNjRoCZchCo3y8+lvTQOO6ZDlAx7XvPUCRY5EkwBAwNzXm9/T+3aCVy2moc2+s4VS1n/abqemDN7uOxL6EYCB/Lm2pcXmscIMJ6Am2iX6tncfQkjFq4b81e7T5O6dNu3V4jgJq8Hma3Su/wlP/GBUUBVeqEMkXlEaRgMKfUgdKH2xOM0iCvrBwvxXZVrZUxBrUK3jSF1aUxR70u6RYRDqXs6R4uDQedMOlf+ZWF8JvYgGzHiPUTWzN/ubN8GCzrfEJ50gX8/NTimpStcQ8fEJEMVq6rozYZICoA3e4LcbooGdQivwBeuT5P+Uzq3GVO2xFwC0LRgIOY5qeXnMtCF/tmHu1tcA7iphNTnYyTj7SzcGjh9daT15wHWZxww5RSOq5cpN8Z4uyHJEAsTKhoyWa2wKnTCrofoh+hTQN8On5UbFuF0hvGgoOTEDHTds/VX18oOnGEOg6tS9CkjjJx+3zFfA7tRw16Uoousdx0pjVhRLSYenu5eaW1peaodnXr7ROnkQnbr4RkrLmdlW2Q8wGbKmOe7JJvVON2o5t+yBM2nkmNOlir4t8Gfnexzq/sPYo77AGUrxNWdHF+YK4X0jaExfbcZ1sQryDu6/FuU5Z9HGa+Exqu2kviYZPEmfzHBd9FUdCEMHfGrOYUC3fYu4XykKJ82FWuID9CcMLp6Y1vDaBDzjiDoXMg4+UfXSzv/y6nVQSw5ebNNRbM7TqeLX/0Atppsp2bVpcIzgltFZ12oJnTGHXxzVpVu2S2vo0zsNVuqaEBAS4DOyu3Skzn4kdJxthKai+4djnildw+U8ulZ9ViZhHEw3qlrRH7Jlkag6l4oQoTK3/8hApuBSuw/uDspyicRMeWembvVrYkal0fBL1oQvrfx3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

