apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBYqdc9koYSwIk+1sO/qcirskV6+KzbgRaySU9nKMQQ9ncmiE/SsLv2zDqWUG9zUPQG3fwhUB7H41lF+3uNrb9sfha23gQJJzPs0qytBepyK3aAcSu0OtZo+0vMsmWVTw9H+AaBHVjPtKmVXLzS84EqUjCTsDlQ0x7U9isdqSUiX4vRU3VQn7tCEqL28RPiwC2iLUtFGvVKS4zI2NPWpWTnRjriDSiH9X0tK701b2OPDDaUttPH0QH6uSPR6DLcoZ7mIBDbyvWrTDpy/SiASMKpTuFnFz1FAgVTNWrfQd4uf8VDfzI4upbXrL61OHyY0QOfKpxP6stnIBzuA7ZTR6axqgbPeRDgYni1iiK16g6VCIqyihBrThlTENXyuIGo5Jk6Cf6kXXm+pqQ/3vUNDYVGP/o/1ZFD9YaSBJYK16Uuz8uAibrHcxaL1IqPdY2uj7iPINZ8r4yup71+okm1IHqwkRg+Uq07diQFogAgVagSM4Py84/GK8dEHuspcX3c5wQ97WxyaIQ+fBpOvbwQw83NwNrKOva5SIc0BzSrQu6YMR6uwiE9RfdXzA2EIehCAIqoX3zlIXgs2SnJ7Ewd8QjlH+706npREgh5D8cid8tLSMsxDmLpIWKvTRKH7xgrzFYL3x23RgWOuxY0Mn4vvc60vDF6pADnxsep7zqA1McODNLRc+JnCUAT/2JyRUA+xanYC3Nt9QmbHcczHiQoVbUA3Hm7pVLFr/C/zdOmgxyiOAop5F++Xi1MOjKKTce787vFifdjba/kvmFhtNAiTglzQAlK8SceQtUdvpOJFGtWy7yEqpMaablE8LPq8WqRzCc/PmZ+tTVVAQUmdCrM2kMyCEK3q9nmVkuL/1fCEEA2GjfEA1Axv3m3ozqIS49SVi7gfWNqRLvR
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

