apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBRSj5G9cjY2vT/JDSXj0NUQmHdBlw/5e4n4rWmjUKoKh1WY2zeKJkNnfFDHoRqED1wmO3jobhJSyVqle3ZJs88QdkD2OEVEH2FLwJnqO2CgXZb3+6rY35P9vyzWF4j46K5r6VIWa4Etb0IWmmhErelDeSgGoT5Wmo3b2VB5WKTza5pDrTacjJPiLDaDURx0m3VRDuR7zqT8W8vr26zY5y9P2TQOuOsanimH51FOnZzBXAAYLpQ/SVwIh1qdMuZMcJE6IN5gpT661MnZZsKiLxcrqtqMokIRHTAntt0FWHn2wyT03UDeoMv7VNuxORMjQ+RaK5p3s+bLNgj6fhlx2xOKx107u+Vd28ZQtXeoUzaslUC7fnUF5grZao10yT/mr/DW+teJM0WZEelFaWQBFZqXXkYoh5xzUCMJNYYK89NReNYCjfoE82d/RS9XOlhzdJ0AFQ5TLf4rDjsqfbLj0IXaA6Vi+9TCvD2yA2NnMVRdSrnJDBIbwk0/HiXdrrv43BO6wJnqyisbyIMlASChRC/kofNcC0ltePQP9L+dqFHmIzvz99VtsWOQqgFGZngNXonWTjnOlnqQt9E/VR23NjvvEG4UaNukCD+qtNig4RfD9MsgwAIUPXiy53BPywpfDVOuenP5m1F1Z4VfL6zMnHQUZs+fQq73oOdddLtKw4wSwb4MuxmPDJcqVIa+kGl3rEd8Knh9ejS+/y2MYtNkp32U5Fq5v6xYTXNG8em64dTHsHPSW7oMEPCKrPpTbNdZB2PPt+AAcuw8aW+WK+Igs0901S4M4A1sH642XJ1wc1ifpGvR5V718CugQvv4UsZnHbcUVrVyq7mFBHCEUvsmnEQkyWvK6JcrHBjBPhxJqhTmdpj6pnPlAHaGUOmH764TnyoAVPOp1z5
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

