apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCRfS3V8uMOSDmOdUwwKTvRLjewTeQF/+pdbbYAse9+RD/pudAWKZST7xdH9nlAf38A9Jjimm3icGC9OCFHPEYeh2L2zknqnzkz2ZA1KpjtZ9sln01P54aBrpR2FHwtdPjVIjkS/EAkyWXp5stwxljYlzfJgcpnk84dfNOGfNVQZ+BLVfTYO2LT7q37PUhQEjy1elAdpCsluViCFCzOIo+F3uXMfGCGuqhSeY1SlI6KDO5qZLEYqQMHfD5WPAbZfK30IjlBcY87ccHTx7czNSstMGU+3z7WJjViqxSgtlYfCzTwTgmCpuYC3DMivoxbpH8u3PJMlhp9aJnStrnaJTiHTcG2N/OPPQB9M59m3dVno5EuVzTfmByIImntVvrfcE9Pxeymo7JfrTJTxkRacKe9ynyyc8wgKEcjIu660I4nhbmfaZNbYY0lHtJ/cB389CzLWNfgbj6pbQU0LinjnUtateFeQfv5jUDpTgevlAjCm1Rck20WmqvWcXn6gzGCjeGcMsg1emTE1HynArUm1533CJbAAnLbTkkIf7fFL2E0lNOrOJd98hli71/0DLHv5XPj9t4jZHVtErkO+UsS+2fw595XDPhfiTkNgb+6cHhoRa8jxgeNwaxDlyMflNMK/nqIG/g3fj4nq1UhmrGcV+isRtcyS3foAW0pDcGXBmyOfkIB5xqvtTTmJtLHjHL+420aOw+0aN5WY4+O3reV0KM6A8z8GDmm/7x/cl08Loiiwq6zdDvVRjSTWQQh30Bp/jR9bbmyiziwpyplWS/ccMJbQMxyW5KDrnxg2CMe0cy+FfeoM7dGAHh6b2IF4rOlnUQvsKNwbe1wcSwqB553sWR1BdDUHwd+Ed3u4bI6KTlwKEV6YwlEbDKjro0MVGoHMp12IjKYyKg9
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

