apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBoUTl7OVKo6Etg36izCjLlbn0PS+J0JVSWbLDms/vmz99BLTVmLv+kU0bVtyP3/L0kHU7L9RPLH1Tv+fVgfLJFna0/f0P3YJeXCgz4Kh1Pljo1E4ij3GZgIP203PHVDzXD7ow88CrcYD2Madstudv0T2dWrHH3gmFdVs0r4bcke7retRCRndPipEjfaTIiQmblHHBxKCs+17YlHXsgK/ahSfQir3/T4Osxj/dudMaOIFX23R/WTkmBsCKB6YKhAQNVLNKbS+16CxHSXdDrTWJjYTnNdGSbvro3mdQQ3OSlpYQXkOaXFqCS/mMAWCz70ojhyKb2TbUfgZ/u4XTMpcxJUn9HzqWf0AN2pU/jpKU+0Gk3Ws+bvCebxKnhwwc+ogLOtnsumY0CBmMB1gGiiw3qn0wrQT+YFW/P2w7376n1w9QyyxsrLJ93JVjdJ+Ro9UbgRa0SjNGn6C44NqufbLr45JRvUcwxkatv69X5cLpY55FGxOShRnpCnqLvS+OjuJzhvXMbNUFB/wo7ju5RWmFBF/bry0vtR7tFd8vfXxunvcLLzn5/zrKYGYTwioLX9aaoPEwQuvjGl+qqSAGT4RAGQy3ynVVfQJL4L/NcY7BJVKI6q+WWHgMDrZs+kAcA+BZ5sC5ijJn1Z4cWveOc7wZHL6klGX3FcMuE0c/S3oJ6F+xq7Me2GyAG/5+f/u09+F4poIBfzVx5uI0NGHP5QlmLKnR0132ypRgb1jFWLe0dtnjNHJBmoPlOgsRjTRdIMX2bgJwW6cXTaFchxcjg5ZPRKI7NuWbDmdrKBjudZJ83GQdlDKpKnOE8d24AKgp31kQLxk6QjqE5wocqm3tiL1Q1xK6rRmcNK0mmZ69mfSzFuhyr1UZDJXgTIbBlsyI39cz0bJr97XzL
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

