apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAXF5LozXR4MAEc430nDY1nPNoZBR+VK9JoxL0qUQO1FSMS10NHxpt3MUyzUvUeZiSkg9KNyzKZ8GfoC/QdTuVArH1n2G+qSm9jv5cDBvRhaAuiVsWPJrroGedkEF8lhG2lieF7Gp6FTtHNg+h9bGFfVIR+yyDGtXjsrHou4t8o1k5LCn44ysA83J+1BJ+Tjw1+hu2tvS7wuYoI022OWu1MKqHqDhiFdTiQ587GIACM1J6Ac4H45LNRJjPmvwomxg1w9oinHmwQkq6HwUYSnjfhNgGn+2fTck0TwHTsnf+NZmuQDbEBRFBD1f8BnoqGALrNqpdHFxIKG78VG7a0wfUkzA8v3KwMDy5C785KM8nei8zZMoaE4a+/3vE0C0HJw120RBWf/hoPRq02IIGwusNtMiwql0JXqhMHS2GvYtiMsLONuUjzVNxwSJ3Ed49jHYmzKmhQ0PJN3mOphoLzSW8d/VGa0awyTtHwHAxUsN0UIlZnlztyHXtPTzDT6Cek2O32Ji0Ey27+lx0VhGnv9h1BpXx3eFwSRa1uukWv2UHkcEF2IPqr0OOqI0bnOtxwU3vOC3G0jWzDnuAgnBQGkCaSulDJ3M3hHGfy9WUpp+zvxK8k6vmq2lq1qA+Jr80JK4A1mCDPoDfe3YIfeeyL6QN/fSl5jFuNXFj/kYRr6+YuLZdDzVzJGqruwYFRAD6qdwRkzQLuc6F8SWFEMTCkTuNU4clmJGP/TNhYPizItXyJSNFZYina4s79s5uMW3n6MswCw3SffZ1xxjHixbVYlsVPeJj9uYAql8YI9EXxtJqwY9Ef3pMQ+sCzjsaVoTpMfocTB1Z2dY5gtvnSNOK4G6RIEDc7bPh4E7vaKoBkLDg638Cl64CZouv1v0FGwaUprdqH9XhFwv6b
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

