apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBW2sDsu3Uw+pqNoQsq5qyuGZXFJ9FAHTnewh2fb1fD3g+hQRJOFgOHw9FdC/edwpScjoBnFrqgXwBU9a59x8pD2nm7FejwMVWPW+nwW2rfiz/t7NgvO07Iawo1gv3zdE0ZdxIhT/brw92X//G6C1iMuhcj3JKCMGemWbUUtkxS0/69vnzGSNviOjA9TwWQulRbuyCsf5Fh42TzqYSXPem/Wn8Wgotw4WnYltBF0e33zP85ptAlzI6Y9A5Hp9NQjwjp9TXfZSkppoYXlD1F5TFqnYIG/dlraXq9y7Vg+Ly7Gmjua18EY5DkHzbLPnKGEC9ptjfTjFDZqPP5patVz5NfEi6o+bjHCYrlk3F4YyNrB5TWlSarghtsC5eUNgI8xd21Ih9ij8QCxs//z5FcnYH4/VHh5jiAkU2AENFcp1uaFwEbQxCFX5HdQ8gH3qs2VYhH6SQOZGUsDjFTjSfojQZeFoNemLvg7cg2SQmRfANemUq4eTnLNnGt82chEbRPsfYAqzfIFpIqQlNZ19Df+o5lN2N4jz6F2hmbU6iaBJYQEE1dOu2Sm1jge9BbJOGub8BcNF/Z1cApSwkTpZGQHtJRVb/5jrynvVZhRvClUTP8M99yvCQBD1fzmxDFwD1NOKVUkhxYACITV6gK/vAafdKMRRhYcbSFPN4IypYSapaAtQOzaT7gFmSneyfKDj9VoRTAiECeCQdxHRij7+V9z/k9dQjeIJUZVfzTf3B28+i+GD5hyy+AAAGU
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

