apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCQkn2tZpt/ngq6W1YSLUosPbVzaEGAMr7awe+dU/X5SImZ44KymRlo+bYWhyyGmQEtjQ9yRYnMmKBpGhkmb66LxlpoSZjAwYq0XZ9kQZsuxZo0scHtgjrnixYs1+LAyojbz/nqi5TQCQKMW42mkG7Inu2ZAwmroSGFCFIji5wFi0rcGRs6xSRRkVSM9aPegrkwMRRWG9a6tRv3bAIocacNjKwftKtCy52PfGQt8yk3QYumq61nwQGIMESkwpoAOGDWw1nLK15ODoL5cJAuJQN4PnL5MlBtUqLx10RTU8wDNNL9nb8NWBhP6zV1hEBd0udpBw39BhDcAwLCQ/5ooz9f1eeFreExtfbWDzcU7s2dhOe9SVG3IHZaaJjhFAHfNnw82TyfAlF5rse9odEdVURYhfWLnF1DnzYibebdOm0Sfod51zsRnISDSYhMBQ0TVJtX561OL2LtzdUqF7S3NHylUUezsT2wrduJtlj1QC2fkoe7OY6P5EY4/F37LUZzi5h0OapE6NOrfnG94GwxfgNpnkSQq12af2shRTYhs888XPubZepdSIibUzTxEU2vrxSYQh3or58a4T1e3OA8Dxge+Lbyv6ugZl4/p7M1lOfd8aq/XngXT0r/+M9hmKsbirr1pbpNqo0XWsdb3vf4GawLUiymkQsx/pgemL+sZ/nkBRuOei84WNS096ch8rIbV9n5KpFfsbqPhGwbbOmoqUVwH6kH/kBJF8ppTrEDKe4WGWE/jlBWksWh
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

