apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAfhfchw8wnkJ/9Mt+RNFCBASNGpQtB10fL2KQ5/GvnuTbRTTwKBeaDIHOLAC4KTF2Jw8G/ryI882h0KQlDzrm61m9POfMty93e/Dlowg8SRNTllS1M6Ei33i4vFxt28yR4sHlTwgqRZnMeU15pC02MoIQQrFlR3cT9TFYpb0AvfU9mLVLfJSkz8aMseUCrFDRdMnNxTZ8ujVWEfE6sYxLSV3wgAlQ7Dw3LG4A7r3yeHTZn5Gp5dhuZMmOuef7Ky3OgblH/vOtrXIULwRkCB7hbZSXPqDN/wynodN+8Y3BJbPWmlizjbG+FuTPjS066iZWxHNJnlLR1MbpC+i7Q4U2598mEQ1zX4eADgarZ+f0txYVT/2ZvC0INpEVfw/UDhd/Y2iiubcUQGalkOmHyIzUxoSAG8roRK6AbDWxmqToL1e1TWxUw2SGgB/AifYXwUy2P+/nUC+tk/1DdK/sfYXqwHE7yhmB2GvISQEHyZRd3XFdhi+ahutJnotHwk5XfvmEhLiWig9jl80/zmJIixNw23jBxLMRbpSMuQfVLDMYIIlCa3v9zEt7a4v/vSQnCklo1rgTrOyERzVBi8mUtr8oJoxm9cieCnGyngbWmEO9WydfWH4TuUcXUnaqM7Vk3aD206h/p0OFoDwzfCJdLa+sIiX+a+3vCnvSHZzP2ApvYTIInWB+VxnphIHGyyi3DTu+Xhs4P2fMWtNYls7+hoWEp0hXpJo2hqZU+OqQ++J48CWvUI9YfXR7j
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

