apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAZhCPEex21+R/KFD9GIdLvd3FwF0pbZghfL/f7qLiytwkkcTunfKZwx/8SE1kKBafoPMtOjwKXhgcvCipHnzWDDkNw2D7UPNZ1mRpbkOWibEcQ4VXVc6Fq4K+QviN+tRc1UYd40vw+ItqC4LAjnS9nwJohteVDR0L+6IH4c0ypAcVJciWi3mOAOll2R2oIq54A5PpRjKI1m5AucO6gd4h8MUTPG6AdaZXiogCyHz+FcDrDGJXWfT6FwVjId9DbFDTE3RlLW/58FMCY7gghwGpHW/7dCS0Q3StucAUvWX8i8JvW7krWTIwqblGfioWjVNnYO3/rphaiQpjpWTIsxyRdnD4NmR5K4/ZtzA+XRgxKUkG7OQos+Af53aI8z2fDF3SIAB4+HRW+3JSUuSl8GgP0u7VuFlesoHfEFyjz+J5Q5oVETcKFlwqL4jKw7p59RwGsJPaezw2U1171SK2JY3LjCjMmsHz8fTnkCRss/mHiQ/oMgOw+x09a9IZA0b3GF3D5gTFJrpqglCNlApO+1mifJ6B27HR4HSIeZgC0fZLRCeW6F9/Q2GD6onLwe7WtJVAU0XsBRaeq0HzXwPtWEdnaVXdYpurQ6DJnC/Aa1d2okIM4gmt6hZtmGLKfClXg45GZt0EF52x052IrTIg6kGfUuZXJ1V5sKOB3w60Tm2zZ1FMmw/BkABjhubAiM7/7DteroPDt2+y6cYpwlgsmZ7MgMDAY6sQ5nOYmxR15crO6tCf1LmNU1RL+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

