apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBdGjHy51MKKkoGyJdj6rae9vYHQa1IRZpWF+Xh+AUqHDM6G6Ry1PSleGGHHXOh5N286GvOjsfpbnj7eRW0KywuVPc7lAXSVVwHjAAU57WnKadx/NrMzGYBMi88P0J42gGRnDzaqDGEkGHQS7sfAGrQZYZEQyY5U21EJ1LvQaWgUyeO15vyTjTkkFiGpWqpDBnie+7k6TUI9ht3OBr/qLNDo+Dxdn22CgLtej0BV/duWI112a3HErBJ36wjBocn7EuoYCha2aGvIGL8lvkbrhmcIaYyMwY1JfAXLlDRvB5Kog3UaZDW2ltyr12B2MbZH7GO8b/ziMT24hcqFHLmx3gIfhVI+cPnVyVCweQxougFBIm+76brR75yd0DuA9F5n12CuvYJFGzjajttFkCvhHbGF87KhWMruxp99db3OJOIqfnEIGxw5l0pdDIw+1comRTvZa5A3SKl06E5qFvo+p4SMVrbgKiz84UW5iNqS+knUMQt7Hwkc953/Uy5nhvozWz76tRuhnW55glWUQb+vvcMPDxnK5mQMFDvOpc0zRECcyrTyT94g9bMHecNKmC0k6wQQS1nf2q4hzOTMXYpJVFpl8JVfRBNiy32wbJKESgRNwcltutNLpw3EhpOmuhoO05EEqb+fZqdOs1Fmhv5nue7BuY2WH0zGuiK+KKk5Dow7kres8O8l+GI/qb9VdsaVAGmV0q0luBWbj+p5PxaBT1toxTMpe8XseXngqC/q/hg/cNnDiVkgUFg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

