apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBVBjTp0j12hluaA6SpWvDd5ZySXVGmtSHVjoUOCIcvbvO+dTtZND90IBZn9TnAvb5VmkERxOJCwAhJAD9kvokA1ub2GJ6g1hfkN1hoSjbs3zl3++ym71227qGIA60VnCa+ZLemQdZVyhBgMHNWkPFrTe1GM/GWMtKQtxcjNrqC3FOAScfH0HnKR7JetHKZ9ez8E2lmK/KgWWz0MSIbnuaF3bPido5TsNhpC/BrSZiNPmfwhrS5xDIVTdjIMjfY6/BMEX8O4L6qrcbOY0iMbX631jmCqTceN9pSANl/D6kC5HI//SZckWOJ3CyEYo6WbbOvKz9uwNvWDT9RE5Owmdwy7tXA2chayBoawAteIAJEFgz2PAO2MhQz1JRDh555R63wK/Ov4ykRVVQa+oeIiXV/EDrbMTu95Yt5+fCpZIX6XpygkLFev9iiU3svYWRVX9yN389UPyalY1RKC0rpXEj6gTfNo0vUkNXGnp1/Lq6jwwugEB+JiT518RNamHIhU+NM7B/qIXar+dx70h2nOpoCd+85qWcYysH09eBEG/i6q9GmdXz/9NL7Vxo3EGG5nwk/5lgsyI/3UHqIKgvvHmFUWwuw6lk9LjHx/dmai+zOzPa6CkmNwd+bZxpLcMH4i3PDjnfNvVRzt2NecYlPv9+N0Lm6Ey7J7mp27uU88TqxVIHW1lWbHhmn8zsUsjY6/FCurB4FKMoCm3QNC1ViVys3ZTj2fKaoGJVQHVe0/qy9OYfXaPsj1QuN
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

