apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgA+Uz3j5xCjWuf/4Ui+qt9Rm/lX8INhtmsFi7jgNxM9WgAz7IUVDhwDJDuLaAVYDeXBVgOg8aiuSAE6sMXyHcF5CcbedJRattr8MvMdjdXLksRwuqseVG8mdam05VcG68vGPY67jlZgiPWXSWEVe9p7er+DH6zhDXC6tPdRZEKpOq268OmXQ5LTlmuc/zDhoMpDfC11GbWsQTAIstSrim1BoIeiwIAsd/YhNyhbBBFAvlB9aYoEbwwUbPXt3/ac+Ik2D0pgC6yjZVHDZ4QDDwM163RjzwvaDkG0aX05VXwumk/eavhpX7LqU6qo6dsY8Wibs0Gr0dSamhUjlOccZ+dUzga50SjHqA41gMFQo2zJi3fQV2HlyMIaVFMB4i77fGaE5A4z6lDpVJVF+wgxyOWOua+EfeM6NTJRt42gl8IZjmMwtg/CMeTkNLfp+waHTzxJx/epCf7RCcbZIu1bB9QZ8ApaB2Pq6lv2/+lkr5wCY3T0Vm+m40xPEgNBnwoPpor6+vvZvaNPgbxyEpmhiSmb0ExPumhnu1FeQ5Ughb6hKNExW2kQNCXnkB8pyAbmL4kUFFK7OKqCEiLkhxMfTEwzcCvuKShWg1axrOJqi+fcI899lvWnWvxc9zlrJPglO4iXHMNqxGTmqCR0udPo/+q9c/tbzm7efWh0asUr3UnLcDSUS+M4NC5teXLyS+0Jg7MZiJjeZnHXtemP+/tX+qI2JRDaoB4ZBu8DMMLYFaOiydgFQ1Boz7tw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

