apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgB8hzCdGGj0QsOemj+i2xFGB/zIZYY2BGVd7q0eo14oOXi09uz7JtbOdlyYrLG23b/uNNb6axBFnW2cUo/jURYkG2p35k5lcgBeBf02pFAj/FBgN+yxwunxBvYmcYFyY2i9K+ebgT8H44E9tIkSSdb+uvc7rAG+fgS8JqD8iP4sty5MYGdP+451CHrWCG8zcX8guuidZvSXGJZ8dvXhE+Gc2zmeBqxuXLy0p5n+sQ1gX57PeGQNs/UUAXo8aGyUqYLdLUP8KLmTQiCF57sZtF8c+ZJgw0k5t59g4nfIT9ngHhzsKRF8PacAyn4FM0eE/0BYiJbBQeCQWJg6FfPXnYBtvBEpIJRAE9BkKOwVEaTPM23lUZFjrHo0/AX9RbBlq0AbdCGY8QXY8FUSjUMWr8u0PrdG9LNR1BgphIC+dp0ni/TC8JntyijkJCQWKspPeMfScAI+TxpcZNAX8w+NJkz3xDVlFZGGhMSc+mSqRDcycx64jpImuOwSKM+PY+/1TqCKYN7MTt02655gFFGJlnK0WqlWOjfdjBDksoibdjnHgiLLlPz5RPWfqip5kr67g9WeVRXfGi9JKJ8dnw8bLYFCYPhrNLE2jB9GymMLvuZ6V7y28Kw9sL4KC8quk/8UAZ66gYRkMnguivgKlnVjhOwskcNmXZDvW2WWer0F1HtkcnCEEB0IJDgJUrQz70VjJ49qxmjsLdLCBb/eOZ6hbXO+AIHgAfssG9NUThyn5zHOFX1gET8c2IDq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

