apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBrtrfTOankrYeArD/mxD/PyO3rTwup5MGwMfTnxbeL9+7h6+UoQVNSRtZDUd39DeD9uxPK8JFG3wqDPTM4FTAi9dHAl9TLh83NDaHiwQwEMOW7ZLqhdFmaVGyWKOjX202vx2JGddgS2UVWYvD0QhRbFkaL5X3DK9Jmt0huSdN6RzNxn7aSJ9i+Q6GUIKu0gWwQHdoyYQUbf+CqXGz2cZZUst4RiyaWoQDCyIsBcRkmNQF5HuQLffiir41RtBqR05A8wJECIMC0RB665TcMawlKVB58Bk0V5T5XLubYu/hvklp4I6api5/rUjgR6fs/vgU0fAwFvR3U5Ba1Yg76YJR66NzOq8T2argAYBiqPvPDOvX7ppwVmGEq11q2IkIZJW+U4a3uWrWymRQ6l6DYBCeKgbg2W/paURqZhzicAmsGABXJo8I9Xr9mt+7inUpgnhiPJVHAiYlnguXq2LQbQw7ksKX8j0FKrvAHJgXRYtT0rFeaiJ0FW1RlS8Ns3E1TgCSgZfbJ13lTGTkER27SJrOXM2ihdMuVhn5toOPMhlmnX964Om2CNm0SRe/Mm8L/8Z8ifpOKMXL+PjVH0FFVYYN72w8tnT8vg7jT9MM68drwn90Mp8K8a2qZzTPEOXkNZDFp7x7c7XUsZhZ383j1Duoalg6wkxladFAIx47fosdEsnYQydXx5qpLvbVT4TqT0FjAONup7yaE9IobSQ8JM+haKRYDklN/MOfSZglyhHdZJW76136NeKPp
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

