apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCvaSemcHTm1MlFROfYMDpAbjXYrAkZGhlIQMQOgXlOXtFrQh8Dso8YcqjBIMg7CzQu/nFrpHqyPUQdAV4pcjvx+yERs/FDTff9yFgceec70WkkxPAmL4tV2buwz3NRNLtC72rMf6HDJpAC0xUmsaxRFxLRn9eHjP4wcLGMVpi3jr0D67j61bSCkMjf3+kO+qo+M0JTGimm6GMg0G020JdIY1OnJWlJUtEe8lygZWGHfLBBiHiobCodZkUbAp8AT4l3JUo3oGlrfapSH0cFtCrhMORjP2MVG889mfQU4VHN+eSyo1RMg/5/FKhpUUV8ocTD2dFvwPv0FAaRWGcUhBHw5tjkc+OwThIwYcf2dc8pcyF3Ahutf8rIjQwfO2tUcenBvfcKmB0oAghOFrOjPuSyw6unKXhQa1tbSc6VDriUBJ8e4PgkoqP281FLVrR0+/PxEAITRSAFn+NKOdGkRJWXA23dB+N7z1c7jENblvd2tlLor/dv2gS6dwCEd59jKMEWsPU2oFAWlnvvv0GMO9FoeI030TTxhvIsAIQbpWXA5IBMqCQuk6V8UAo8eSmwW2lIOUIKKmXhzjK13e7OHpnz0WidQpknTUlmWdgvqXMw3JInzNciIheLXoXYR43RHEIG/aTmr+zLXHLZWz33u2RtoHYRI2PdcNCbN4dQrxQQcfDwLSURGAhhYMIFjMgG/Yui5e7PCwU8zkicbeQ7k3KxVBWhdvdzSbrUZn1UDr3Irnm/jKV8hFB8
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

