apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCZyHBDul5wPqtpurSTHv4A5qpUYsYy1xwIlzhhtIFv6vbu7ausXUyMq7tQeXxo2f0g+Zf6gOgLBGm2m9ePHq4SupZGZrnGQaIF2wjiB9B5QUfzkKnTBwWSAW19ucHXx7zarUA3sR5X6wZfqY+Y3iFyqlXBvGYbGdGkXRwjE5P3IGP4Q3pRW0PLSJ8bKgtfF4wrvG5Oo4bhDfkyx/7BWjwlqD79seDnhFbp+Z1fo5h1Ip5oL91Ec8wejoB9mOmj3xUyBsSItY2/0F9xEuFNHknQXLoz6A4j0RQZD+V+EkVoq/MBOSK87Uz2aYZv7zFW1zI4ib8LYynU2GdRxm2ld7QqJ/mh6vJEaFIwiFjJ8Eskcs+7wBcSA9aXJvxq3XJsrqp8B7ZeVnasdRwr+vfAdEKdaysSluszgoaEKfubyb5b2at2yTuBCThSqyU579QxiwC91hJcojogPG6FoTv96rGbhPf/P9SndjZRT6+P9+vB/sUjn97GlvsMlhqGm1cSK8qK2400Cz6CDZ/0qnmgdchHuYaX9sRmsHlWknK2m1+NfoMqCd69/Ip+HcivxnYAqswEQxQ0tENz1GIxrwL0059AwFQJX0gr8uJtfan6fuKGlrYt3wTB4gHEibzPR4QdVZEJLEhWpebHZD8vyyGksD0ZaL5KRQAcpwlFlWU0Y/BYFveR+uNCrQAIXNt1S3xs+Unc4vSKZ8ymr1NRAr5TgvuRgHRZbFOmBY81dfahiGaYR3BSdQTORikj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

