apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBiabVIf9oO+jrwkXbugQMGAvSMW74mj0JOtMquEylApMWMrd5Zi3q5MzNVnf0hY3owKf4nJncK+jslKuelO/GRM9kGGOy/N+4mU5K+NzeeDihXUZVkc1t32oVY0mELsX2pJLaCJqZu1bibfYA6swBvpQQiN5p6giuNFvgPVZliNXRvYsLFNW2s9YTQxXoZaRkSPI6lHiw6NMWFZVf/u5+3PsTjfQ8e59PP6B7WrC6tCMoakx+A5UkG4/+07wPBFTGN0AR/XHcNKFQTZg7CbCsDXsjQYWpsn7pRWxPcAgeApxxsMn59C86gnZQ1L6O5zY9PkoJA7dCv/PVk20dIHOB6Kj3eNsaDyuvUlNzhZmVmISSyYFmZAXSG24ewKlICzr8YBkAggGmvoiypMqx9KLj6fSH+y7M+Y23UuIKC4DS7m+TrXPfsivRbAA1hp8mDUfveVyviy1IZsfU/L22m6OYZwCogepIijpjI4CoxzAwa3OPN14FVJi1KBHK5MbNbqT3ljagyooGX/ww7kibXfuOCWa1fXvC6v1PlKXnqFI96vmrqq7Dhh0fbRdmflJ6RsazegtZ6RSvmOlmbR7rahjUrmG5LXFQ0TVpd1eVIrgPzqpJf+P6uIk7kKdrkSs3WeilVkcf85nqP7CSxgZx2ajRgdKpY9paxBr0msw9xMMPwSBMDWcRKIqfJI/GSV+53YqI54m5c0R2vWDsfnTf/AdiRQ0KQ60js2FnSYndzhOUqGWwRIVyI1TAj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

